In [1]:
import numpy as np
from scipy import sparse
import scipy.linalg as linalg

In [32]:
R = np.array([[1,0,1], [1,0,0], [1,1,0]])
b = np.array([0,0,0])
q = np.array([50, 60, 10]).astype(float)

In [33]:
sol, res, rank, s = linalg.lstsq(R, b)

In [34]:
o = q - sol

In [35]:
R_null = linalg.null_space(R)

In [36]:
p =  R_null @ (R_null.T @ o) 

In [37]:
A = sparse.csc_matrix([
              [1, 1, 0, 0, 0, 0, 0, 0, 0, 0], 
              [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
              [0, 1, 0, 1, 0, 1, 0, 1, 0, 1]]).astype('int8')

x = np.zeros(10)
b = np.array([0.3*300, 100, 200])

# Ahora definimos una distribucion prior: 
# En el último mes, lo vendido fue
q = np.array([50, 60, 10, 20, 40, 20, 4, 7, 12, 40]).astype(float)

In [38]:
sol + p

array([0., 0., 0.])

In [39]:
np.linalg.inv(R)

array([[ 0.,  1.,  0.],
       [ 0., -1.,  1.],
       [ 1., -1., -0.]])

In [70]:
#A @ q

In [71]:
# Ejemplo: tenemos 5 clientes con 2 productos cada uno
# Las restricciones serán: el cliente 1 no puede tener mas del 30% del total 
# el presupuestp del producto 1 es 100
# el presupuesto del producto 2 es 200

# Tenemos entonces un vector binario de largo q = clientes * productos
# Cada fila representa: (cl1) p1 p2 (cl2) p1 p2 (cl3) p11 pl2 (cl4) p1 p2 (cl5) p1 p2

In [72]:
q_ = q.copy()

In [74]:
# resultado anterior, diferencia
A @ q_, A @ q_ - b, 

(array([110., 116., 147.]), array([ 20.,  16., -53.]))

In [75]:
q_

array([50., 60., 10., 20., 40., 20.,  4.,  7., 12., 40.])

In [79]:
# Tenemos distintas posibilidades:
# 1) recorrer las restricciones en orden y llevar cada una a 0. Este proceso tiene dos partes: 1) forward, llevar el grupo a 0. 2) back, llevar el resto a la misma cantidad
# 2) tomar la restriccion más insatisfecha, llevar esa a 0 y repetir
# 3) usar el vector de diferencias para multiplicar cada subconjunto por un lr diferencial ponderado por la diferencia a esa restriccion

In [ ]:
q = solve(A, q, b)

In [83]:
import os; os.chdir('..')
import sqlalchemy
from time import strftime
from variables import *
from data2sql import *

ModuleNotFoundError: No module named 'variables'

In [2]:
%%time
#lst_to_sql(lst_path, lst_cols, tabla_hist, n=1, mode='replace')

Wall time: 0 ns


In [11]:
from sqlalchemy import inspect

In [ ]:
for table_name in inspector.get_table_names():
    print(table_name)

In [66]:
%cd ..

C:\Users\mgrinberg\Desktop\disc c\SDPC\SDPC\SDPC


In [84]:
from variables import *
from SDPC_utils import *
from data2sql import *

import pickle as p

ModuleNotFoundError: No module named 'variables'

In [85]:
TMP_PATH = r'C:\Users\mgrinberg\Desktop\disc c\SDPC\SDPC\tmp\\'
from scipy import sparse
import numpy as np
import pandas as pd


KeyboardInterrupt



In [ ]:
A, x, b, idx_ineqs = [TMP_PATH + p for p in ['A.npz', 'x.gz', 'b.gz', 'idx_ineqs.gz']]
A = sparse.load_npz(A).astype(bool)
x = np.loadtxt(x).astype('float64')
b = np.loadtxt(b).astype('int32')
idx_ineqs = np.loadtxt(idx_ineqs).astype('int32')
print('Datos cargados.')

In [89]:
dif = ([1/10] + list(np.ones(b.shape[0] - 1)))

b_ = b * dif

In [94]:
write_sol(x)
validar()

Guardando resultado en Q1.csv
Volcando resultado en Análisis.
Ingresando resultados en Restricciones.
Errores en restricciones con indices [  3  14  22  36  54  55  64  72  80  93 104 105 117 131 138 140 158 166
 167 172 176]


In [87]:
q = x
lr = 0.01
epochs = 10
lim=10
verbose=False
cvx = False
polish = False
precision=0.01
live = False

In [83]:
b = b_
i = 0
rows = A.shape[0]
idx_eqs = [i for i in range(rows) if i not in idx_ineqs]
while True:
    if np.all(abs(b[idx_eqs] - A[idx_eqs] @ x) < abs(b[idx_eqs])*precision) & np.all(A[idx_ineqs] @ x <= (b[idx_ineqs] * (1 + precision))):
        print('Todas las restricciones satisfechas.')
        break   
    print('Epoch: ', j)
    for i in range(rows):
        a = A[i].toarray().ravel()
        q[a] *= (b[i]/(q @ a))
        print(i, b[i] - (q @ a))

Todas las restricciones satisfechas.
